// AppConstants.swift
// Copyright © RoadMap. All rights reserved.

import Foundation

/// Строковые данные для всего приложения
struct AppConstants {
    // MARK: - Constants

    static let photoFeedTabBarTitle = "Лента"
    static let notificationsTabBarTitle = "Уведомления"
    static let profileTabBarTitle = "Профиль"

    static let photoFeedTabBarImage = "Домик"
    static let notificationsTabBarImage = "Уведомление"
    static let profileTabBarImage = "Профиль"

    static let nameImageLeftItem = "Логотип"
    static let nameImageRightItem = "Сообщения"

    static let storiesIdentifier = "StoriesCell"
    static let postIdentifier = "PostCell"
    static let recommendIdentifier = "RecomendCell"

    static let nameAvatar = "Аватарка"
    static let nameStories = "Ваша история"
    static let avatarLavanda = "Аватар лаванда"
    static let redCircle = "Красный круг"
    static let avatarHourse = "Парень и лошади"
    static let nameUser = "tur_v_dagestan"
    static let postImage = "Горы"
    static let commentImage = "Комментарий"
    static let likeImage = "Лайк"
    static let saveImage = "Фложок"
    static let sendImage = "Стрелка"
    static let countLike = "Нравится: 201"
    static let discription =
        "tur_v_dagestan Насладитесь красотой природы. Забронировать \n тур в Дагестан можно уже сейчас!"
    static let commented = "Комментировать ..."
    static let publicationTime = "10 минут назад"
    static let secondPage = "Река"
    static let thirdPage = "Море"
    static let nameImage = "Девушка в платье"
    static let nameUserReccomend = "mary_pol"
    static let titleReccomend = "Рекомендуем вам"
    static let rightTitle = "Все"
    static let subscribeText = "Подписаться"
    static let secondAvatar = "Закат"
    static let secondNameUser = "сrimea_082"
    static let commentIdentifier = "CommentCell"
    static let SubscriptionIdentifier = "SubscriptionCell"
    static let notificationTitle = "Уведомления"
    static let requestTitle = "Запросы на подписку"
    static let lavandaUser = "lavanda123"
    static let commentText = " понравился ваш комментарий: 'Очень красиво!'"
    static let todayHeader = "    Сегодня"
    static let thisWeekHeader = "    На этой неделе"
    static let commentSecond = " понравился ваш комментарий: 'Это где?'"
    static let commentFirst = " упомянул(-а) вас в комментарии: @rm Спасибо!"
    static let mihoUser = "12miho"
    static let commentThird = " появился(-ась) в RMLink. Вы можете быть знакомы"
    static let buttonTitle = "Вы подписаны"
    static let commentFourth = " понравился ваш комментарий: 'Ты вернулась?'"
    static let commentFive = " подписался(-ась) на ваши новости "
    static let markUser = "markS"
    static let neitUser = "sv_neit"
    static let time = " 12 ч"
    static let threeDays = " 3 д "
    static let fiveDays = " 5 д "
    static let sevendays = " 7 д "
    static let eightDays = " 8 д "
    static let avatarMiho = "Miho"
    static let avatarMark = "Марк"
    static let avatarNeit = "Нейт"
    static let lobi = "Лоби"
    static let see = "Берег"
    static let closeText = "Закрыть"
    static let plus = "+"
    static let line = "Полосы"
    static let plusRight = "Плюс"
    static let lock = "Замок"
    static let profileTitle = "mary_rmLink"
    static let infoIdentifier = "ProfileInfoCell"
    static let currentStoriesIdentifier = "CurrentStoriesCell"
    static let photoIdentifier = "PhotoCell"
    static let surname = "Мария Иванова"
    static let countPost = "67"
    static let countFollowers = "458"
    static let countsubscriptions = "120"
    static let post = "публикации"
    static let followers = "подписчики"
    static let subscriptions = "подписки"
    static let consultant = "Консультант"
    static let change = "Изменить"
    static let share = "Поделиться профилем"
    static let shareImageName = "Share"
    static let launch = "Запуск"
    static let moon = "Луна"
    static let astronaut = "Космонавт"
    static let space = "Космос"
    static let lights = "Огни"
    static let earth = "Земля"
    static let rocket = "Ракета"
    static let takeoff = "Взлет"
    static let urlSpacex = "www.spacex.com"
    static let storiesRocket = "Ракета взлет"
    static let previous = "Назад"
    static let next = "Вперед"
    static let update = "Обновить"
    static let buttonName = "Крестик"
}
